import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ["var(--font-heading)"],
        body: ["var(--font-body)"],
        sans: ['"Open Sans"', 'system-ui', 'sans-serif'],
        display: ['"Open Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ["var(--font-size-xs)", { lineHeight: "var(--line-height-xs)" }],
        s: ["var(--font-size-s)", { lineHeight: "var(--line-height-s)" }],
        m: ["var(--font-size-m)", { lineHeight: "var(--line-height-m)" }],
        l: ["var(--font-size-l)", { lineHeight: "var(--line-height-l)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--line-height-xl)" }],
        xxl: ["var(--font-size-xxl)", { lineHeight: "var(--line-height-xxl)" }],
        sm: ["var(--font-size-s)", { lineHeight: "var(--line-height-s)" }],
        base: ["var(--font-size-m)", { lineHeight: "var(--line-height-m)" }],
        lg: ["var(--font-size-l)", { lineHeight: "var(--line-height-l)" }],
        "2xl": ["var(--font-size-xxl)", { lineHeight: "var(--line-height-xxl)" }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground))",
        },
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "hsl(var(--success-foreground))",
        },
        error: "var(--color-error)",
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: "var(--color-info)",
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          helper: "var(--color-text-helper)",
          placeholder: "var(--color-text-placeholder)",
          link: "var(--color-text-link)",
        },
        bg: {
          page: "var(--color-bg-page)",
          layer01: "var(--color-bg-layer-01)",
          layer02: "var(--color-bg-layer-02)",
          layer03: "var(--color-bg-layer-03)",
        },
        borderToken: {
          subtle: "var(--color-border-subtle)",
          strong: "var(--color-border-strong)",
        },
        gray: "var(--color-gray)",
        orange: "var(--color-orange)",
        teal: "var(--color-teal)",
        alert: {
          info: {
            text: "var(--color-alert-info-text)",
            bg: "var(--color-alert-info-bg)",
            border: "var(--color-alert-info-border)",
          },
          success: {
            text: "var(--color-alert-success-text)",
            bg: "var(--color-alert-success-bg)",
            border: "var(--color-alert-success-border)",
          },
          warning: {
            text: "var(--color-alert-warning-text)",
            bg: "var(--color-alert-warning-bg)",
            border: "var(--color-alert-warning-border)",
          },
          error: {
            text: "var(--color-alert-error-text)",
            bg: "var(--color-alert-error-bg)",
            border: "var(--color-alert-error-border)",
          },
        },
        segment: {
          1: "var(--color-segment-1)",
          2: "var(--color-segment-2)",
          3: "var(--color-segment-3)",
          4: "var(--color-segment-4)",
          5: "var(--color-segment-5)",
        },
        stat: {
          basic: "var(--color-stat-basic)",
          gain: "var(--color-stat-gain)",
          loss: "var(--color-stat-loss)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        successState: "hsl(var(--success))",
        warningState: "hsl(var(--warning))",
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "var(--border-radius-sm)",
      },
      boxShadow: {
        "1": "var(--shadow-1)",
        "2": "var(--shadow-2)",
        "3": "var(--shadow-3)",
        "4": "var(--shadow-4)",
        "5": "var(--shadow-5)",
        "elevation-1": "var(--shadow-1)",
        "elevation-2": "var(--shadow-2)",
        "elevation-3": "var(--shadow-3)",
        "elevation-4": "var(--shadow-4)",
        "elevation-5": "var(--shadow-5)",
      },
      spacing: {
        none: "var(--spacing-none)",
        "token-1": "var(--spacing-1)",
        "token-2": "var(--spacing-2)",
        "token-3": "var(--spacing-3)",
        "token-4": "var(--spacing-4)",
        "token-5": "var(--spacing-5)",
        "token-6": "var(--spacing-6)",
        "token-7": "var(--spacing-7)",
        "token-8": "var(--spacing-8)",
        "token-9": "var(--spacing-9)",
        "token-10": "var(--spacing-10)",
        "token-11": "var(--spacing-11)",
        "token-12": "var(--spacing-12)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(100%)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.25s ease-out",
        "slide-out-right": "slide-out-right 0.25s ease-out forwards",
        "fade-in": "fade-in 0.2s ease-out",
      },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
